version: '3.5'

volumes:
  postgres: ~

services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: alfa_battle
      POSTGRES_USER: alfa_battle
      POSTGRES_PASSWORD: qwe123
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"