server:
  port: ${SERVER_PORT:}

logging:
  level:
    root: INFO

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
